# 日志配置
logging:
  level:
    root: info
    # spring security 日志级别
    org:
      springframework:
        security: DEBUG
  config: classpath:logback-spring-test.xml

spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_data?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    # hikari
    hikari:
      connection-test-query: SELECT 1
      ## 最小空闲连接数量
      min-idle: 5
      ## 连接池最大连接数，默认是10
      max-pool-size: 15
      ## 连接池名称
      pool-name: MyHikariCPOfMaster
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 20000
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      is-auto-commit: true