# 日志配置
logging:
  level:
    root: INFO
    # spring security 日志级别
    org:
      springframework:
        security: DEBUG
  config: classpath:logback-spring-test.xml

spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_data?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    # hikari
    hikari:
      connection-test-query: SELECT 1
      ## 最小空闲连接数量
      min-idle: 5
      ## 连接池最大连接数，默认是10
      max-pool-size: 15
      ## 连接池名称
      pool-name: MyHikariCPOfMaster
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 20000
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      is-auto-commit: true

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）mapper 和dao要在同一级目录下
  mapper-locations: classpath:mapper/**/*.xml
  # 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.huangrx.template.po
  # 以下配置均有默认值,可以不设置(实体中设置后，这里不生效)
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID"; ASSIGN_ID 雪花算法生成id
      id-type: auto
  configuration:
    # 不开启二级缓存
    cache-enabled: false
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


authorization:
  token-header: Authorization
  token-prefix: 'Bearer '
  token-subject-access: access-token
  token-subject-refresh: refresh-token
  secret-key: huangrxnikezhenshitaishuail1014
  access-expire-time: 24
  refresh-expire-time: 720
  login-user-key: login-user
  token-type-key: token-type

security:
  ignored:
    urls:
      - /user/register
      - /login
      - /nav/acquire
      - /document/acquire
      - /palette/acquire
      - /chat/answer
      - /timeline/acquire
      - /subcategory/acquire
